### ISSUE TITLE
What's the difference between this repo and jamischarles/5to6

### ISSUE THREAD

**Issue by tomchentw** [5to6/5to6-codemod#10]
Hi @xjamundx,

Thanks for the hard work to bring this to reality.

I've noticed that it's forked from jamischarles/5to6. Could you briefly introduce what's the difference? Currently I only noticed that:

* This package is published on npm for name [5to5-codemod](https://www.npmjs.com/package/5to6-codemod)
* This package is searchable from [Google with keyword](http://lmgtfy.com/?q=es6+module+codemod). Yes, I came here because of this.

Again, thanks for the hard work! Very appreciate this.

**Comment by xjamundx** [comment]
Oh Jamis is my co-worker and we talked about this and worked on it a bit as a private repo before I took his code and combined it with a bunch of other transforms I'd written. I don't think his is a published or maintained thing, it was just more for fun. I wrote to github and asked them to remove the `forked from` tag!

**Comment by tomchentw** [comment]
Got it. Thanks! This is really awesome. Will try to use it today!
