### ISSUE TITLE
Leading comments duplicated, trailing newlines removed

### ISSUE THREAD

**Issue by JamieMason** [5to6/5to6-codemod#18]
Hi,
Thanks for this great project. While trying it out I noticed that comments at the start of a file get duplicated when any `5to6-codemod`s are run on them, also trailing newlines are removed.
#### Example 1

![dupe-comments](https://cloud.githubusercontent.com/assets/320492/15105518/3e104258-15ba-11e6-9687-d6560c90befe.png)
#### Example 2

![dupe-comments2](https://cloud.githubusercontent.com/assets/320492/15105533/65527142-15ba-11e6-8b70-7f11c59f88d6.png)

**Comment by xjamundx** [comment]
Thanks for these notes, not sure how yet, but I'd love to fix these :)

**Comment by slorber** [comment]
Hi,

I've also noticed such behavior.

**Comment by slorber** [comment]
Related issue:
https://github.com/facebook/jscodeshift/issues/44

**Comment by xjamundx** [comment]
Appreciate the updated information

**Comment by slorber** [comment]
hey, someone added a solution to this issue here and the official recipe has been updated: https://github.com/facebook/jscodeshift/issues/44#issuecomment-271825342
https://github.com/facebook/jscodeshift/pull/181

**Comment by gmathieu** [comment]
Fix was merged with #31 and #30 rewrote how comments are handled.
