### ISSUE TITLE
undefined does not match field "value": string | boolean | null | number | RegExp of type Literal

### ISSUE THREAD

**Issue by mladenp** [5to6/5to6-codemod#23]
I am getting this error when i try to transform imports from cjs.js
`Error: undefined does not match field "value": string | boolean | null | number | RegExp of type Literal`
But from 190 files i get that error only of 3 of them, but i can't find any significant difference between those 3 files.
Here is one file where it fails: [http://pastebin.com/C5K01b7M](http://pastebin.com/C5K01b7M)

**Comment by xjamundx** [comment]
Thanks for the report @mladenp, the pastebin link doesn't seem to be working

**Comment by mladenp** [comment]
I found out, its require statement, like this:
`require('../components/css/font-awesome.css');
`

**Comment by xjamundx** [comment]
Great can you get me a sample file that will fail and I'll try to get it fixed!

**Comment by mladenp** [comment]
Try [this one](http://hastebin.com/axibonokig.js), that's the same as the one above.

**Comment by xjamundx** [comment]
Here's the line it can't handle:

```
require ('es6-promise').polyfill();
```

I'm not even sure how we could handle that... 🤔

**Comment by xjamundx** [comment]
In the mean time I'll work toward at least a better error message with clear instructions :)

**Comment by xjamundx** [comment]
published as `+ 5to6-codemod@1.1.3`
