### ISSUE TITLE
Handling cjs inline requires

### ISSUE THREAD

**Issue by gmathieu** [5to6/5to6-codemod#29]
Converting our legacy code, I found these weird cases which cause a few exceptions. I would consider all except `var Foo = require('Foo')` to be inline requires which es modules isn't meant to support.

Given that modules should only be imported at the the top level, should we assume any requires past the top level are inline? Or is that too simplistic an approach?

```
describe('foo', function () {
    var Foo = require('Foo')
    beforeEach(function () {
        this.foo = require('foo')
        var test = new fn(require('foo'))
    })
})
var LOOKUP = {
  	foo: require('foo'),
	get bar () { return require('bar') },
}
```

I'm happy to open a PR, just wanted to get some direction first. 

Thanks for this tool, it's really helpful.

**Comment by xjamundx** [comment]
Thanks for the idea!

This one is really tricky and depends on the use case.

For example here some people may want the experimental new `import("filename")` function which returns a `Promise` and keep it inline. Others may be able to actually just bring it to the top of the file.

I don't think we can solve this in a way that works for people. It's too hard to guess what might work for them. :-/

Also, there are a lot of lint rules that suggest not doing this, so unless it's an extraordinary use case, it may not be good idea to begin with ;)
http://eslint.org/docs/rules/global-require

**Comment by gmathieu** [comment]
@xjamundx  thanks for the quick respond. I think we're saying the same thing but I didn't express it properly. Currently, the cjs transforms looks for requires everywhere. I'd like to update it so it only looks at requires at the top level.

#### include these:
```
// CJS top comment

var jamis = require('jquery');
var $ = require('jquery'); // end of line comment will get eaten
var $ = require('jquery');
require('something');
fn(require('something'));

var foo = bar;

// some comment
var jamis = 'bar',
    _ = require('lodash'),
    lodash = require('underscore'),
    bar,
    foo = 'bar',
    $ = require('jquery');

var routeTo = require('../routeHelper').routeTo;
var fetch = require('../someUtil').pluck;
var {includes, pick} = require('lodash');
```

#### ignore these:
```
describe('foo', function () {
    var Foo = require('Foo')
    beforeEach(function () {
        this.foo = require('foo')
        var test = new fn(require('foo'))
    })
})
var LOOKUP = {
  	foo: require('foo'),
	get bar () { return require('bar') },
}
```

Would that work?

**Comment by xjamundx** [comment]
Oh yeah that makes sense. We should only grab top-level `require` for sure!

**Comment by gmathieu** [comment]
Great! I'll get a PR going.

**Comment by gmathieu** [comment]
Resolved

**Comment by xjamundx** [comment]
published and all that

**Comment by cawabunga** [comment]
Hi there, I faced a problem seems it caused by this feature. I have so code:
```javascript
import angular from 'angular';

export default angular.module('foo', [
    require('bar')
]);
```
Is there a way to transform code to:
```javascript
import angular from 'angular';
import bar from 'bar';

export default angular.module('foo', [
    bar
]);
```
Thank you in advance!
