### ISSUE TITLE
Add TravisCI

### ISSUE THREAD

**Issue by xjamundx** [5to6/5to6-codemod#3]

**Comment by amilajack** [comment]
This can be closed

**Comment by gmathieu** [comment]
> This is not an active repository
> You don't have sufficient rights to enable this repo on Travis. Please contact the admin to enable it or to receive admin rights yourself.

@xjamundx could you allow travis CI's integration with this repo and require builds to be passing before merge? Thanks

**Comment by jsnmoon** [comment]
Any updates on this?

**Comment by jsnmoon** [comment]
Hi @xjamundx, I've gone ahead and enabled Travis CI for my [fork of 5to6](https://travis-ci.org/jsnmoon/5to6-codemod) (as well as other project level improvements like [versioning NPM scripts](https://github.com/jsnmoon/5to6-codemod/blob/master/package.json#L8-L9), [release tags](https://github.com/jsnmoon/5to6-codemod/releases), and [project badges](https://github.com/jsnmoon/5to6-codemod/blame/master/README.md#L1)). I would love to carry over some of these enhancements upstream to this repository with your permission.

**Comment by xjamundx** [comment]
@jsnmoon yes please :)

**Comment by xjamundx** [comment]
https://travis-ci.org/5to6/5to6-codemod
