### ISSUE TITLE
named-export-generation does not handle string literals as keys

### ISSUE THREAD

**Issue by jgable** [5to6/5to6-codemod#46]
Thanks for your work on this set of codemods, it's saved me at least a day of work already.

I noticed a weird behavior when using the `named-export-generation` transform on some code that has exports like;

```
module.exports = {
  'one': 1,
  'two': 2,
};
```

It looks like the transform is only accounting for keys that are of type `Identifier` and should be updated to handle keys of type `Literal` as well.

**Comment by xjamundx** [comment]
Good catch!
